// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramDesigner.Infrastructure;

#nullable disable

namespace ProgramDesigner.Infrastructure.Migrations
{
    [DbContext(typeof(ProgramDesignerDbContext))]
    partial class ProgramDesignerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgramDesigner.Domain.ProgramNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrerequisiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ProgramNodes", (string)null);

                    b.HasDiscriminator<string>("NodeType").HasValue("ProgramNode");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProgramDesigner.Domain.GroupNode", b =>
                {
                    b.HasBaseType("ProgramDesigner.Domain.ProgramNode");

                    b.Property<int?>("ChoiceCount")
                        .HasColumnType("int");

                    b.Property<int>("Rule")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Group");
                });

            modelBuilder.Entity("ProgramDesigner.Domain.StepNode", b =>
                {
                    b.HasBaseType("ProgramDesigner.Domain.ProgramNode");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Step");
                });

            modelBuilder.Entity("ProgramDesigner.Domain.ProgramNode", b =>
                {
                    b.HasOne("ProgramDesigner.Domain.GroupNode", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ProgramDesigner.Domain.GroupNode", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
